# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1V1iRIyP6yIRuhqpq8FKVEEmBwlIqig
"""

a= 1
b = 1

a+b

a-b

a*b