# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1V1iRIyP6yIRuhqpq8FKVEEmBwlIqig
"""

x = str("длинна ребра куба")

x = 2

print (x)

x**3

x*2