# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/138_XcWnksjhhssRsb4M6Lz8wXI9tAiHB
"""

a = 4
b = 4

(a+b)/2

(a*b)**0.5