# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1V1iRIyP6yIRuhqpq8FKVEEmBwlIqig
"""

x=1
y=2

abs(x)/(1+abs(x*y))-abs(y)/(1+abs(x*y))