# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1V1iRIyP6yIRuhqpq8FKVEEmBwlIqig
"""

a = 3
b = 4

(a**2+b**2)**0.5

0.5*a*b